version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: roomdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: roomdb

  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    ports:
      - '8080:8080'   
      - '50000:50000' 
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false

volumes:
  pgdata:
  jenkins_home:
